"""
Vendors ROBUST_AGENT_BASE.py into kev/multi_agents/robust_agent_base.py so it's
importable as `kev.multi_agents.robust_agent_base` from any deployment
(container, AWS, etc.) without depending on a sibling `shared_resources`
checkout being present at a specific relative path.

Also adds a stateless `invoke()` entry point: the original RobustAgent is
designed as a long-running, queue-processing worker (start()/stop(), a
background asyncio loop, a 30s heartbeat task). That model doesn't fit a
stateless server where an agent is instantiated fresh per request and may
run on any replica. `invoke()` calls handle_message() directly -- no
background tasks, no shared state -- and captures whatever the agent would
have sent via send_message() so the caller gets a normal return value.
"""
from pathlib import Path

SRC = Path(r"C:\Users\kpasc\source\repos\constellation\shared_resources\docs\scripts\ROBUST_AGENT_BASE.py")
DST = Path(r"C:\Users\kpasc\source\repos\constellation\kev\multi_agents\robust_agent_base.py")

STATELESS_ADDITION = '''
    # ------------------------------------------------------------------
    # Stateless invocation (added for KEV's stateless-server deployment).
    # The methods above (start/stop/_process_messages/_heartbeat_monitor)
    # assume a long-lived worker process. invoke() bypasses all of that:
    # it runs handle_message() once, directly, with no background tasks,
    # so a fresh agent instance can be created per request on any replica
    # and safely discarded afterwards.
    # ------------------------------------------------------------------
    async def invoke(
        self,
        message_type: "MessageType",
        payload: Dict[str, Any],
        sender_id: str = "api",
    ) -> Dict[str, Any]:
        """Process a single message statelessly and return the result.

        No background loop, no heartbeat, no persistent queue -- safe to
        call on a fresh instance on any server/replica/lambda invocation.
        """
        self._captured_responses: List[Dict[str, Any]] = []
        was_running = self.is_running
        self.is_running = True  # allow send_message()/_deliver_locally() to work
        message = AgentMessage(
            sender_id=sender_id,
            sender_type=self.agent_type,
            recipient_id=self.agent_id,
            message_type=message_type,
            payload=payload,
            timestamp=datetime.utcnow(),
        )
        try:
            await self.handle_message(message)
            return {
                "agent_id": self.agent_id,
                "status": "success",
                "responses": self._captured_responses,
            }
        except Exception as exc:  # noqa: BLE001
            logger.error(f"Agent {self.agent_id} invoke() failed: {exc}", exc_info=True)
            return {
                "agent_id": self.agent_id,
                "status": "error",
                "error": str(exc),
            }
        finally:
            self.is_running = was_running

    async def _deliver_locally(self, message: "AgentMessage"):
        """Capture messages sent during invoke() instead of dropping them."""
        if not hasattr(self, "_captured_responses"):
            self._captured_responses = []
        self._captured_responses.append({
            "recipient_id": message.recipient_id,
            "message_type": message.message_type.value,
            "payload": message.payload,
        })

'''

def main():
    if not SRC.exists():
        raise SystemExit(f"Source file not found: {SRC}")

    text = SRC.read_text(encoding="utf-8")

    marker = "    def get_status(self) -> Dict[str, Any]:"
    if marker not in text:
        raise SystemExit("Could not find insertion point (get_status) in source file")

    text = text.replace(marker, STATELESS_ADDITION + marker, 1)

    header_old = "System: Constellation - Robust Agent Base Class"
    header_new = (
        "System: Constellation - Robust Agent Base Class\n"
        "Vendored copy: auto-generated by kev/scripts/vendor_robust_agent_base.py\n"
        "Source: shared_resources/docs/scripts/ROBUST_AGENT_BASE.py\n"
        "Do not edit by hand where avoidable -- re-run the vendor script instead."
    )
    text = text.replace(header_old, header_new, 1)

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text(text, encoding="utf-8")
    print(f"Wrote {DST} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
