"""
Copyright (c) 2025 Sans Mercantile
All rights reserved.

This software is proprietary and confidential.
Unauthorized copying, distribution, or use is strictly prohibited.

Patent Pending - Sans Mercantile Constellation AI System
International Patent Application Filed

Licensed under Sans Mercantile Proprietary License
For licensing inquiries: legal@sansmercantile.com

System: Constellation - Robust Agent Base Class
Vendored copy: auto-generated by kev/scripts/vendor_robust_agent_base.py
Source: shared_resources/docs/scripts/ROBUST_AGENT_BASE.py
Do not edit by hand where avoidable -- re-run the vendor script instead.
Purpose: Base class for all robust agents across the constellation
Author: Sans Mercantile AI Development Team
"""

import asyncio
import logging
import json
import os
import sys
from typing import Optional, Dict, Any, List, Union
from datetime import datetime
from enum import Enum
from dataclasses import dataclass
from abc import ABC, abstractmethod

# Configure logging
logger = logging.getLogger(__name__)

class AgentType(Enum):
    """Enumeration for different agent types across the constellation."""
    ANCESTRAL = "ancestral"
    FINANCIAL = "financial"
    MEDICAL = "medical"
    EDUCATIONAL = "educational"
    SECURITY = "security"
    OPERATIONAL = "operational"
    GOVERNANCE = "governance"
    COMMUNICATION = "communication"
    ANALYSIS = "analysis"
    COORDINATION = "coordination"

class AgentState(Enum):
    """Enumeration for agent operational states."""
    IDLE = "idle"
    ACTIVE = "active"
    PROCESSING = "processing"
    ERROR = "error"
    SHUTTING_DOWN = "shutting_down"
    MAINTENANCE = "maintenance"

class MessageType(Enum):
    """Enumeration for message types."""
    TASK = "task"
    DATA = "data"
    ALERT = "alert"
    DIRECTIVE = "directive"
    RESPONSE = "response"
    HEARTBEAT = "heartbeat"
    STATUS_UPDATE = "status_update"

@dataclass
class AgentMessage:
    """Standardized message structure for inter-agent communication."""
    sender_id: str
    sender_type: AgentType
    recipient_id: str
    message_type: MessageType
    payload: Dict[str, Any]
    timestamp: datetime
    priority: int = 1  # 1=low, 5=high
    correlation_id: Optional[str] = None

class RobustAgent(ABC):
    """
    Robust base class for all agents in the Sans Mercantile Constellation.
    
    This class provides the foundational architecture for building resilient,
    adaptive, and transparent AI agents across all systems. It includes:
    - Async message processing and communication
    - State management and error handling
    - Self-healing and adaptive learning capabilities
    - Governance compliance and ethical decision-making
    - Transparency and explainability features
    - Performance monitoring and optimization
    """
    
    def __init__(
        self,
        agent_id: str,
        agent_type: AgentType,
        message_broker=None,
        llm_client=None,
        persona: Optional[Dict[str, Any]] = None,
        config: Optional[Dict[str, Any]] = None
    ):
        """Initialize the robust agent with core capabilities."""
        self.agent_id = agent_id
        self.agent_type = agent_type
        self.persona = persona or {}
        self.config = config or {}
        
        # Core state management
        self.state = AgentState.IDLE
        self.is_running = False
        self.start_time = None
        self.last_heartbeat = None
        
        # Communication infrastructure
        self.message_broker = message_broker
        self.llm_client = llm_client
        self.task_queue = asyncio.Queue()
        self.processing_task = None
        
        # Performance and health metrics
        self.metrics = {
            'messages_processed': 0,
            'errors_count': 0,
            'last_error': None,
            'uptime': 0,
            'performance_score': 1.0
        }
        
        # Robust capabilities
        self.healing_protocols: List[str] = [
            'reset_connection',
            'restart_module', 
            'clear_cache',
            'fallback_mode'
        ]
        
        self.governance_rules: List[str] = [
            'ethical_compliance',
            'data_privacy',
            'resource_limits',
            'decision_transparency'
        ]
        
        # Adaptive learning
        self.learning_rate = 0.1
        self.performance_history: List[float] = []
        self.feedback_buffer: List[Dict[str, Any]] = []
        
        # Error handling and resilience
        self.error_handlers = {
            'connection_error': self._handle_connection_error,
            'processing_error': self._handle_processing_error,
            'resource_error': self._handle_resource_error,
            'timeout_error': self._handle_timeout_error
        }
        
        # Agent-specific capabilities are initialized lazily -- see
        # _ensure_capabilities_initialized(). Every generated subclass
        # overrides _initialize_capabilities() as `async def`, so it
        # cannot safely be called (and awaited) from a synchronous
        # __init__. Calling it here unawaited was a bug in the original
        # template: the coroutine was created and immediately discarded,
        # so specialized setup (model loading, data sources, parameter
        # config) never actually ran for any agent.
        self._capabilities_initialized = False
        
        logger.info(f"RobustAgent {self.agent_id} ({self.agent_type.value}) initialized")
    
    def _initialize_capabilities(self):
        """Initialize agent-specific capabilities. Override in subclasses
        (subclasses commonly override this as `async def`, which is why
        it's only ever invoked through _ensure_capabilities_initialized())."""
        pass

    async def _ensure_capabilities_initialized(self):
        """Run _initialize_capabilities() exactly once, awaiting it if the
        subclass implementation is a coroutine. Safe to call from both
        start() (long-running mode) and invoke() (stateless mode)."""
        if self._capabilities_initialized:
            return
        result = self._initialize_capabilities()
        if asyncio.iscoroutine(result):
            await result
        self._capabilities_initialized = True
    
    async def start(self):
        """Start the agent's operation."""
        if self.is_running:
            logger.warning(f"Agent {self.agent_id} is already running")
            return
        
        await self._ensure_capabilities_initialized()

        self.is_running = True
        self.state = AgentState.ACTIVE
        self.start_time = datetime.utcnow()
        
        # Start message processing loop
        self.processing_task = asyncio.create_task(self._process_messages())
        
        # Start heartbeat monitor
        asyncio.create_task(self._heartbeat_monitor())
        
        # Initialize agent-specific startup logic
        await self._on_startup()
        
        logger.info(f"Agent {self.agent_id} started successfully")
    
    async def stop(self):
        """Stop the agent's operation gracefully."""
        if not self.is_running:
            logger.warning(f"Agent {self.agent_id} is not running")
            return
        
        self.is_running = False
        self.state = AgentState.SHUTTING_DOWN
        
        # Cancel processing task
        if self.processing_task:
            self.processing_task.cancel()
            try:
                await self.processing_task
            except asyncio.CancelledError:
                logger.info(f"Agent {self.agent_id} processing task cancelled")
        
        # Execute cleanup logic
        await self._on_shutdown()
        
        self.state = AgentState.IDLE
        logger.info(f"Agent {self.agent_id} stopped gracefully")
    
    async def send_message(
        self,
        recipient_id: str,
        message_type: MessageType,
        payload: Dict[str, Any],
        priority: int = 1
    ):
        """Send a message to another agent or topic."""
        if not self.is_running:
            logger.warning(f"Agent {self.agent_id} cannot send messages - not running")
            return
        
        message = AgentMessage(
            sender_id=self.agent_id,
            sender_type=self.agent_type,
            recipient_id=recipient_id,
            message_type=message_type,
            payload=payload,
            timestamp=datetime.utcnow(),
            priority=priority
        )
        
        try:
            if self.message_broker:
                await self.message_broker.publish_message(message)
            else:
                # Fallback to direct queue delivery for local testing
                await self._deliver_locally(message)
            
            self.metrics['messages_processed'] += 1
            logger.debug(f"Agent {self.agent_id} sent {message_type.value} to {recipient_id}")
        
        except Exception as e:
            logger.error(f"Agent {self.agent_id} failed to send message: {e}")
            await self._handle_error('connection_error', str(e))
    
    async def _process_messages(self):
        """Main message processing loop."""
        logger.info(f"Agent {self.agent_id} message processing loop started")
        
        while self.is_running:
            try:
                # Wait for message with timeout
                message = await asyncio.wait_for(
                    self.task_queue.get(),
                    timeout=1.0
                )
                
                self.state = AgentState.PROCESSING
                
                # Process the message
                await self.handle_message(message)
                
                self.task_queue.task_done()
                self.metrics['messages_processed'] += 1
                self.state = AgentState.ACTIVE
                
            except asyncio.TimeoutError:
                continue  # Normal timeout, continue loop
            except asyncio.CancelledError:
                logger.info(f"Agent {self.agent_id} message processing loop cancelled")
                break
            except Exception as e:
                logger.error(f"Agent {self.agent_id} error processing message: {e}", exc_info=True)
                await self._handle_error('processing_error', str(e))
                self.metrics['errors_count'] += 1
        
        logger.info(f"Agent {self.agent_id} message processing loop ended")
    
    @abstractmethod
    async def handle_message(self, message: AgentMessage):
        """
        Abstract method to be implemented by subclasses.
        Handles specific message processing logic for each agent type.
        """
        logger.info(f"Agent {self.agent_id} received {message.message_type.value} from {message.sender_id}")
        pass
    
    async def _heartbeat_monitor(self):
        """Monitor agent health and send periodic heartbeats."""
        while self.is_running:
            try:
                await asyncio.sleep(30)  # Heartbeat every 30 seconds
                self.last_heartbeat = datetime.utcnow()
                
                # Update uptime
                if self.start_time:
                    self.metrics['uptime'] = (self.last_heartbeat - self.start_time).total_seconds()
                
                # Send heartbeat message
                await self._send_heartbeat()
                
            except Exception as e:
                logger.error(f"Heartbeat monitor error for {self.agent_id}: {e}")
    
    async def _send_heartbeat(self):
        """Send heartbeat message to monitoring system."""
        heartbeat_payload = {
            'agent_id': self.agent_id,
            'agent_type': self.agent_type.value,
            'state': self.state.value,
            'uptime': self.metrics['uptime'],
            'messages_processed': self.metrics['messages_processed'],
            'errors_count': self.metrics['errors_count'],
            'performance_score': self.metrics['performance_score']
        }
        
        await self.send_message(
            recipient_id="monitor",
            message_type=MessageType.HEARTBEAT,
            payload=heartbeat_payload
        )
    
    async def receive_feedback(self, feedback: Dict[str, Any]):
        """Receive and process feedback for adaptive learning."""
        logger.info(f"Agent {self.agent_id} received feedback: {feedback}")
        
        # Store feedback for batch processing
        self.feedback_buffer.append({
            'feedback': feedback,
            'timestamp': datetime.utcnow()
        })
        
        # Trigger adaptive learning
        await self._adaptive_learning()
    
    async def _adaptive_learning(self):
        """Implement adaptive learning based on feedback."""
        if not self.feedback_buffer:
            return
        
        # Process recent feedback
        recent_feedback = self.feedback_buffer[-10:]  # Last 10 feedback entries
        
        # Calculate performance score
        if recent_feedback:
            performance_scores = [
                fb['feedback'].get('performance_score', 1.0) 
                for fb in recent_feedback
            ]
            avg_performance = sum(performance_scores) / len(performance_scores)
            
            # Update performance metrics
            self.metrics['performance_score'] = avg_performance
            self.performance_history.append(avg_performance)
            
            # Trigger adaptation if performance is declining
            if len(self.performance_history) > 3:
                recent_trend = self.performance_history[-3:]
                if all(score < 0.7 for score in recent_trend):
                    await self._trigger_adaptation()
    
    async def _trigger_adaptation(self):
        """Trigger adaptive mechanisms based on performance."""
        logger.warning(f"Agent {self.agent_id} triggering adaptation due to low performance")
        
        # Implement adaptation strategies
        await self.apply_healing_protocol('clear_cache')
        await self._optimize_parameters()
    
    async def apply_healing_protocol(self, protocol_name: str, params: Dict[str, Any] = None):
        """Apply self-healing protocol to recover from errors."""
        logger.info(f"Agent {self.agent_id}: Applying healing protocol '{protocol_name}'")
        
        if protocol_name not in self.healing_protocols:
            logger.warning(f"Unknown healing protocol: {protocol_name}")
            return
        
        try:
            if protocol_name == 'reset_connection':
                await self._reset_connection()
            elif protocol_name == 'restart_module':
                await self._restart_module()
            elif protocol_name == 'clear_cache':
                await self._clear_cache()
            elif protocol_name == 'fallback_mode':
                await self._enable_fallback_mode()
            
            logger.info(f"Healing protocol '{protocol_name}' applied successfully")
        
        except Exception as e:
            logger.error(f"Failed to apply healing protocol '{protocol_name}': {e}")
    
    async def evaluate_action_compliance(self, action_data: Dict[str, Any]) -> bool:
        """Evaluate action against governance rules."""
        logger.info(f"Agent {self.agent_id}: Evaluating action compliance")
        
        # Implement governance checks
        for rule in self.governance_rules:
            if not self._check_governance_rule(rule, action_data):
                logger.warning(f"Action violates governance rule: {rule}")
                return False
        
        return True
    
    def _check_governance_rule(self, rule: str, action_data: Dict[str, Any]) -> bool:
        """Check specific governance rule."""
        # Implement rule-specific checks
        if rule == 'ethical_compliance':
            return action_data.get('ethical_score', 1.0) >= 0.8
        elif rule == 'data_privacy':
            return not action_data.get('contains_pii', False)
        elif rule == 'resource_limits':
            return action_data.get('resource_usage', 0) < 100
        elif rule == 'decision_transparency':
            return 'explanation' in action_data
        
        return True
    
    async def generate_explanation(
        self,
        decision_context: Dict[str, Any],
        decision_outcome: Dict[str, Any]
    ) -> str:
        """Generate human-readable explanation for decisions."""
        logger.info(f"Agent {self.agent_id}: Generating decision explanation")
        
        if not self.llm_client:
            return self._generate_basic_explanation(decision_context, decision_outcome)
        
        try:
            prompt = f"""
            As a {self.agent_type.value} agent, explain the following decision clearly and concisely.
            
            Context: {json.dumps(decision_context, indent=2)}
            Outcome: {json.dumps(decision_outcome, indent=2)}
            
            Focus on key factors and expected impact. Avoid technical jargon.
            """
            
            explanation = await self.llm_client.generate_content(prompt)
            return explanation
        
        except Exception as e:
            logger.error(f"Failed to generate LLM explanation: {e}")
            return self._generate_basic_explanation(decision_context, decision_outcome)
    
    def _generate_basic_explanation(
        self,
        context: Dict[str, Any],
        outcome: Dict[str, Any]
    ) -> str:
        """Generate basic explanation without LLM."""
        return f"Decision made based on {list(context.keys())} resulting in {list(outcome.keys())}"
    
    # Error handling methods
    async def _handle_error(self, error_type: str, error_message: str):
        """Handle errors using appropriate error handler."""
        self.metrics['last_error'] = error_message
        
        if error_type in self.error_handlers:
            await self.error_handlers[error_type](error_message)
        else:
            logger.error(f"Unhandled error type '{error_type}' in agent {self.agent_id}")
    
    async def _handle_connection_error(self, error_message: str):
        """Handle connection errors."""
        await self.apply_healing_protocol('reset_connection')
    
    async def _handle_processing_error(self, error_message: str):
        """Handle processing errors."""
        await self.apply_healing_protocol('clear_cache')
    
    async def _handle_resource_error(self, error_message: str):
        """Handle resource errors."""
        await self.apply_healing_protocol('fallback_mode')
    
    async def _handle_timeout_error(self, error_message: str):
        """Handle timeout errors."""
        logger.warning(f"Timeout in agent {self.agent_id}: {error_message}")
    
    # Abstract methods for subclasses to implement
    async def _on_startup(self):
        """Called when agent starts. Override in subclasses."""
        pass
    
    async def _on_shutdown(self):
        """Called when agent stops. Override in subclasses."""
        pass
    
    async def _reset_connection(self):
        """Reset connections. Override in subclasses."""
        pass
    
    async def _restart_module(self):
        """Restart internal modules. Override in subclasses."""
        pass
    
    async def _clear_cache(self):
        """Clear internal cache. Override in subclasses."""
        pass
    
    async def _enable_fallback_mode(self):
        """Enable fallback operating mode. Override in subclasses."""
        pass
    
    async def _optimize_parameters(self):
        """Optimize internal parameters. Override in subclasses."""
        pass
    
    async def _deliver_locally(self, message: AgentMessage):
        """Deliver message locally for testing. Override in subclasses."""
        pass
    

    # ------------------------------------------------------------------
    # Stateless invocation (added for KEV's stateless-server deployment).
    # The methods above (start/stop/_process_messages/_heartbeat_monitor)
    # assume a long-lived worker process. invoke() bypasses all of that:
    # it runs handle_message() once, directly, with no background tasks,
    # so a fresh agent instance can be created per request on any replica
    # and safely discarded afterwards.
    # ------------------------------------------------------------------
    async def invoke(
        self,
        message_type: "MessageType",
        payload: Dict[str, Any],
        sender_id: str = "api",
    ) -> Dict[str, Any]:
        """Process a single message statelessly and return the result.

        No background loop, no heartbeat, no persistent queue -- safe to
        call on a fresh instance on any server/replica/lambda invocation.
        """
        self._captured_responses: List[Dict[str, Any]] = []
        was_running = self.is_running
        self.is_running = True  # allow send_message()/_deliver_locally() to work
        message = AgentMessage(
            sender_id=sender_id,
            sender_type=self.agent_type,
            recipient_id=self.agent_id,
            message_type=message_type,
            payload=payload,
            timestamp=datetime.utcnow(),
        )
        try:
            await self.handle_message(message)
            return {
                "agent_id": self.agent_id,
                "status": "success",
                "responses": self._captured_responses,
            }
        except Exception as exc:  # noqa: BLE001
            logger.error(f"Agent {self.agent_id} invoke() failed: {exc}", exc_info=True)
            return {
                "agent_id": self.agent_id,
                "status": "error",
                "error": str(exc),
            }
        finally:
            self.is_running = was_running

    async def _deliver_locally(self, message: "AgentMessage"):
        """Capture messages sent during invoke() instead of dropping them."""
        if not hasattr(self, "_captured_responses"):
            self._captured_responses = []
        self._captured_responses.append({
            "recipient_id": message.recipient_id,
            "message_type": message.message_type.value,
            "payload": message.payload,
        })

    def get_status(self) -> Dict[str, Any]:
        """Get current agent status and metrics."""
        return {
            'agent_id': self.agent_id,
            'agent_type': self.agent_type.value,
            'state': self.state.value,
            'is_running': self.is_running,
            'uptime': self.metrics['uptime'],
            'messages_processed': self.metrics['messages_processed'],
            'errors_count': self.metrics['errors_count'],
            'performance_score': self.metrics['performance_score'],
            'last_heartbeat': self.last_heartbeat.isoformat() if self.last_heartbeat else None
        }